// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { normalizeConnectionString } from "./src/lib/database-url";
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

loadEnv({ path: ".env.local" });
loadEnv({ path: ".env" });

const databaseUrl = process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl ? normalizeConnectionString(databaseUrl) : databaseUrl,
  },
});
